print("**** Welcome to the tip calculator! ****")
bill = float(input("What was the total bill? Rs."))
tip = int(input("How much percentage of tip would you like to give? 10,12,or 15? "))
no_of_people = int(input("How many people to split the bill? "))
individual_bill = round((bill+(bill*(tip/100)))/no_of_people,2)
print("Each person should pay: Rs.",individual_bill)